language: node_js
os:
- osx
node_js: 10
script:
  - npm install codecov -g
  - npm run vscode:prepublish
  - nyc npm run test
  - mkdir coverage
  - nyc report --reporter=json > coverage/coverage.json
after_success:
  - codecov -f coverage/coverage.json
