language: node_js
os:
- osx
node_js: 10
script:
  - npm install codecov -g
  - npm run vscode:prepublish
  - nyc npm run test
  - mkdir coverage
  - nyc report --reporter=json > coverage/coverage.json
deploy:
  provider: releases
  api_key: API_KEY
  file: cures-condec-jira@0.0.1.vsix
  skip_cleanup: true
  on:
    tags: false
after_success:
  - codecov -f coverage/coverage.json
