language: node_js
os:
- osx
node_js: 10
script:
- npm install codecov -g
- npm run vscode:prepublish
- nyc npm run test
- mkdir coverage
- nyc report --reporter=json > coverage/coverage.json
- vsce package -o cures-condec-vscode.vsix
deploy:
  provider: releases
  token: "$GITHUB_TOKEN"
  skip_cleanup: true
  file: $TRAVIS_BUILD_DIR/cures-condec-vscode.vsix
  on:
    tags: true
    branch: master
after_success:
- codecov -f coverage/coverage.json
env:
  global:
    secure: nJlN6rFliMZ0zmTlbsDFpeaOcJVpGabx/17LE2tZP+chpjuOnMxW7axd7lasoAGkJ7ikRS6dZQiUaIQ0wmVLPp4t/5rWJfaR815917aIeVqvondC+N5cg7318d5bPFa+qWaQMOS4IgMwK5DqPGerA+K4ypHC+Qo/tm9SQdVfN+aWD+TrdUHofGGLiMzpB+Ii5VKXP61emtlFNk6u0pkkDOYkWO1YLwHCz93DsLuXyULecshwUi9xiqmj3kpAT+nKcMuJIs08IbztqxLnMiBjWmfd78uXOt0xVvWRRDEIZPomlVvZGH+xVDGYBKsyFQSQGg1QuHdyCMgoSekVKo51kZ4WnwHgkc2TiwvcV2ki+07kLASAP4+z16mt+JIqCb+xfTw8sCG5mu4QuvqCvWt9We9GGBvUV2+YjZlo3zDUSrjW+QPgQX60ce2iqYItMjFiVOvhHhL6sauGQAs0G8+o6cINuSuCGaMSLdKVPL7muX2eCr+32Hp+DpXOJUSLw//42LRbmxmWHEtfPlsv41JcA7Q6XO3gnwkHuS+B51Szx04y+eVAmU7iAVtgktcXK10oGtmgLgMhYPOfx/x2hMjSSTv+wuiqtciv1Ced5TV7txoImi/EC9i9XxkibURVPqN5RNddAt0JpiNqDHUOReuPRn9Tkvd9OkY0XSZBho8HARs=
