name: Continuous integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
        with:
          node-version: '12'
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm install codecov -g
      run: npm run vscode:prepublish
      run: nyc npm run test
      run: mkdir coverage
      run: nyc report --reporter=text --include=src --exclude src/test
      run: nyc report --reporter=clover --include=src --exclude src/test
      run: vsce package -o cures-condec-vscode.vsix
    - name: Report test coverage via Codecov
      uses: codecov/codecov-action@v1.5.2
      with:
        files: coverage/clover.xml
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Create release on version tags
      uses: marvinpinto/action-automatic-releases@latest
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: cures-condec-vscode.vsix
        automatic_release_tag: ${{ steps.get_version.outputs.VERSION }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
